version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: image_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conecthus_user
      TZ: 'America/Manaus'
    ports:
      - '3307:3306'
    volumes:
      - ./dados_mysql:/var/lib/mysql
    restart: always

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: image_app
#     restart: always
#     env_file:
#       - .env
#     environment:
#       DATABASE_URL: 'mysql://root:root@db:3306/conecthus-user'
#     ports:
#       - '${DOCKER_PORT}:${BACKEND_PORT}'
#     depends_on:
#       db:
#         condition: service_healthy

# networks:
#   default:
#     driver: bridge
